/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ERC721SingleBoxWrapper,
  ERC721SingleBoxWrapperInterface,
} from "../ERC721SingleBoxWrapper";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "uri",
        type: "string",
      },
    ],
    name: "AddToken",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "MintToken",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "tokens",
    outputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "status",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        internalType: "string",
        name: "uri",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061021a806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80634f64b2be14610030575b600080fd5b61004361003e36600461011d565b61005c565b6040516100539493929190610135565b60405180910390f35b600060208190529081526040902080546001820154600283018054929360ff8316936101009093046001600160a01b03169290919061009a906101a9565b80601f01602080910402602001604051908101604052809291908181526020018280546100c6906101a9565b80156101135780601f106100e857610100808354040283529160200191610113565b820191906000526020600020905b8154815290600101906020018083116100f657829003601f168201915b5050505050905084565b60006020828403121561012e578081fd5b5035919050565b6000858252602060ff86168184015260018060a01b0385166040840152608060608401528351806080850152825b8181101561017f5785810183015185820160a001528201610163565b81811115610190578360a083870101525b50601f01601f19169290920160a0019695505050505050565b6002810460018216806101bd57607f821691505b602082108114156101de57634e487b7160e01b600052602260045260246000fd5b5091905056fea26469706673582212206712afe482be6d7e44d36fe00d7eb2d7946c28ce33eed745669b386f0181f63464736f6c63430008020033";

export class ERC721SingleBoxWrapper__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ERC721SingleBoxWrapper> {
    return super.deploy(overrides || {}) as Promise<ERC721SingleBoxWrapper>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ERC721SingleBoxWrapper {
    return super.attach(address) as ERC721SingleBoxWrapper;
  }
  connect(signer: Signer): ERC721SingleBoxWrapper__factory {
    return super.connect(signer) as ERC721SingleBoxWrapper__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERC721SingleBoxWrapperInterface {
    return new utils.Interface(_abi) as ERC721SingleBoxWrapperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC721SingleBoxWrapper {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ERC721SingleBoxWrapper;
  }
}
