/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IFactoryWrapper,
  IFactoryWrapperInterface,
} from "../IFactoryWrapper";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "deployment",
        type: "address",
      },
    ],
    name: "exists",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IFactoryWrapper__factory {
  static readonly abi = _abi;
  static createInterface(): IFactoryWrapperInterface {
    return new utils.Interface(_abi) as IFactoryWrapperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFactoryWrapper {
    return new Contract(address, _abi, signerOrProvider) as IFactoryWrapper;
  }
}
