"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IFactoryWrapper__factory = exports.ICollection__factory = exports.ERC721SingleCollectionFactory__factory = exports.ERC721MultipleCollectionFactory__factory = exports.ERC1155SingleCollectionFactory__factory = exports.CollectionProxy__factory = exports.ERC721UpgradeableWrapper__factory = exports.ERC721SingleCollectionUpgradeable__factory = exports.ERC721MultiCollectionUpgradeable__factory = exports.ERC1155UpgradeableWrapper__factory = exports.ERC1155SingleCollectionUpgradeable__factory = exports.DelegatePay__factory = exports.ERC721SingleBoxWrapper__factory = exports.ERC721MultipleBoxWrapper__factory = exports.ERC1155SingleBoxWrapper__factory = exports.CollectionWrapper__factory = exports.IERC20__factory = exports.TransparentUpgradeableProxy__factory = exports.ProxyAdmin__factory = exports.Proxy__factory = exports.ERC1967Upgrade__factory = exports.ERC1967Proxy__factory = exports.IBeacon__factory = exports.Ownable__factory = exports.IERC165Upgradeable__factory = exports.ERC165Upgradeable__factory = exports.IERC721Upgradeable__factory = exports.IERC721ReceiverUpgradeable__factory = exports.IERC721MetadataUpgradeable__factory = exports.IERC721EnumerableUpgradeable__factory = exports.ERC721EnumerableUpgradeable__factory = exports.ERC721BurnableUpgradeable__factory = exports.ERC721Upgradeable__factory = exports.IERC1155Upgradeable__factory = exports.IERC1155ReceiverUpgradeable__factory = exports.IERC1155MetadataURIUpgradeable__factory = exports.ERC1155SupplyUpgradeable__factory = exports.ERC1155BurnableUpgradeable__factory = exports.ERC1155Upgradeable__factory = exports.OwnableUpgradeable__factory = void 0;
var OwnableUpgradeable__factory_1 = require("./factories/OwnableUpgradeable__factory");
Object.defineProperty(exports, "OwnableUpgradeable__factory", { enumerable: true, get: function () { return OwnableUpgradeable__factory_1.OwnableUpgradeable__factory; } });
var ERC1155Upgradeable__factory_1 = require("./factories/ERC1155Upgradeable__factory");
Object.defineProperty(exports, "ERC1155Upgradeable__factory", { enumerable: true, get: function () { return ERC1155Upgradeable__factory_1.ERC1155Upgradeable__factory; } });
var ERC1155BurnableUpgradeable__factory_1 = require("./factories/ERC1155BurnableUpgradeable__factory");
Object.defineProperty(exports, "ERC1155BurnableUpgradeable__factory", { enumerable: true, get: function () { return ERC1155BurnableUpgradeable__factory_1.ERC1155BurnableUpgradeable__factory; } });
var ERC1155SupplyUpgradeable__factory_1 = require("./factories/ERC1155SupplyUpgradeable__factory");
Object.defineProperty(exports, "ERC1155SupplyUpgradeable__factory", { enumerable: true, get: function () { return ERC1155SupplyUpgradeable__factory_1.ERC1155SupplyUpgradeable__factory; } });
var IERC1155MetadataURIUpgradeable__factory_1 = require("./factories/IERC1155MetadataURIUpgradeable__factory");
Object.defineProperty(exports, "IERC1155MetadataURIUpgradeable__factory", { enumerable: true, get: function () { return IERC1155MetadataURIUpgradeable__factory_1.IERC1155MetadataURIUpgradeable__factory; } });
var IERC1155ReceiverUpgradeable__factory_1 = require("./factories/IERC1155ReceiverUpgradeable__factory");
Object.defineProperty(exports, "IERC1155ReceiverUpgradeable__factory", { enumerable: true, get: function () { return IERC1155ReceiverUpgradeable__factory_1.IERC1155ReceiverUpgradeable__factory; } });
var IERC1155Upgradeable__factory_1 = require("./factories/IERC1155Upgradeable__factory");
Object.defineProperty(exports, "IERC1155Upgradeable__factory", { enumerable: true, get: function () { return IERC1155Upgradeable__factory_1.IERC1155Upgradeable__factory; } });
var ERC721Upgradeable__factory_1 = require("./factories/ERC721Upgradeable__factory");
Object.defineProperty(exports, "ERC721Upgradeable__factory", { enumerable: true, get: function () { return ERC721Upgradeable__factory_1.ERC721Upgradeable__factory; } });
var ERC721BurnableUpgradeable__factory_1 = require("./factories/ERC721BurnableUpgradeable__factory");
Object.defineProperty(exports, "ERC721BurnableUpgradeable__factory", { enumerable: true, get: function () { return ERC721BurnableUpgradeable__factory_1.ERC721BurnableUpgradeable__factory; } });
var ERC721EnumerableUpgradeable__factory_1 = require("./factories/ERC721EnumerableUpgradeable__factory");
Object.defineProperty(exports, "ERC721EnumerableUpgradeable__factory", { enumerable: true, get: function () { return ERC721EnumerableUpgradeable__factory_1.ERC721EnumerableUpgradeable__factory; } });
var IERC721EnumerableUpgradeable__factory_1 = require("./factories/IERC721EnumerableUpgradeable__factory");
Object.defineProperty(exports, "IERC721EnumerableUpgradeable__factory", { enumerable: true, get: function () { return IERC721EnumerableUpgradeable__factory_1.IERC721EnumerableUpgradeable__factory; } });
var IERC721MetadataUpgradeable__factory_1 = require("./factories/IERC721MetadataUpgradeable__factory");
Object.defineProperty(exports, "IERC721MetadataUpgradeable__factory", { enumerable: true, get: function () { return IERC721MetadataUpgradeable__factory_1.IERC721MetadataUpgradeable__factory; } });
var IERC721ReceiverUpgradeable__factory_1 = require("./factories/IERC721ReceiverUpgradeable__factory");
Object.defineProperty(exports, "IERC721ReceiverUpgradeable__factory", { enumerable: true, get: function () { return IERC721ReceiverUpgradeable__factory_1.IERC721ReceiverUpgradeable__factory; } });
var IERC721Upgradeable__factory_1 = require("./factories/IERC721Upgradeable__factory");
Object.defineProperty(exports, "IERC721Upgradeable__factory", { enumerable: true, get: function () { return IERC721Upgradeable__factory_1.IERC721Upgradeable__factory; } });
var ERC165Upgradeable__factory_1 = require("./factories/ERC165Upgradeable__factory");
Object.defineProperty(exports, "ERC165Upgradeable__factory", { enumerable: true, get: function () { return ERC165Upgradeable__factory_1.ERC165Upgradeable__factory; } });
var IERC165Upgradeable__factory_1 = require("./factories/IERC165Upgradeable__factory");
Object.defineProperty(exports, "IERC165Upgradeable__factory", { enumerable: true, get: function () { return IERC165Upgradeable__factory_1.IERC165Upgradeable__factory; } });
var Ownable__factory_1 = require("./factories/Ownable__factory");
Object.defineProperty(exports, "Ownable__factory", { enumerable: true, get: function () { return Ownable__factory_1.Ownable__factory; } });
var IBeacon__factory_1 = require("./factories/IBeacon__factory");
Object.defineProperty(exports, "IBeacon__factory", { enumerable: true, get: function () { return IBeacon__factory_1.IBeacon__factory; } });
var ERC1967Proxy__factory_1 = require("./factories/ERC1967Proxy__factory");
Object.defineProperty(exports, "ERC1967Proxy__factory", { enumerable: true, get: function () { return ERC1967Proxy__factory_1.ERC1967Proxy__factory; } });
var ERC1967Upgrade__factory_1 = require("./factories/ERC1967Upgrade__factory");
Object.defineProperty(exports, "ERC1967Upgrade__factory", { enumerable: true, get: function () { return ERC1967Upgrade__factory_1.ERC1967Upgrade__factory; } });
var Proxy__factory_1 = require("./factories/Proxy__factory");
Object.defineProperty(exports, "Proxy__factory", { enumerable: true, get: function () { return Proxy__factory_1.Proxy__factory; } });
var ProxyAdmin__factory_1 = require("./factories/ProxyAdmin__factory");
Object.defineProperty(exports, "ProxyAdmin__factory", { enumerable: true, get: function () { return ProxyAdmin__factory_1.ProxyAdmin__factory; } });
var TransparentUpgradeableProxy__factory_1 = require("./factories/TransparentUpgradeableProxy__factory");
Object.defineProperty(exports, "TransparentUpgradeableProxy__factory", { enumerable: true, get: function () { return TransparentUpgradeableProxy__factory_1.TransparentUpgradeableProxy__factory; } });
var IERC20__factory_1 = require("./factories/IERC20__factory");
Object.defineProperty(exports, "IERC20__factory", { enumerable: true, get: function () { return IERC20__factory_1.IERC20__factory; } });
var CollectionWrapper__factory_1 = require("./factories/CollectionWrapper__factory");
Object.defineProperty(exports, "CollectionWrapper__factory", { enumerable: true, get: function () { return CollectionWrapper__factory_1.CollectionWrapper__factory; } });
var ERC1155SingleBoxWrapper__factory_1 = require("./factories/ERC1155SingleBoxWrapper__factory");
Object.defineProperty(exports, "ERC1155SingleBoxWrapper__factory", { enumerable: true, get: function () { return ERC1155SingleBoxWrapper__factory_1.ERC1155SingleBoxWrapper__factory; } });
var ERC721MultipleBoxWrapper__factory_1 = require("./factories/ERC721MultipleBoxWrapper__factory");
Object.defineProperty(exports, "ERC721MultipleBoxWrapper__factory", { enumerable: true, get: function () { return ERC721MultipleBoxWrapper__factory_1.ERC721MultipleBoxWrapper__factory; } });
var ERC721SingleBoxWrapper__factory_1 = require("./factories/ERC721SingleBoxWrapper__factory");
Object.defineProperty(exports, "ERC721SingleBoxWrapper__factory", { enumerable: true, get: function () { return ERC721SingleBoxWrapper__factory_1.ERC721SingleBoxWrapper__factory; } });
var DelegatePay__factory_1 = require("./factories/DelegatePay__factory");
Object.defineProperty(exports, "DelegatePay__factory", { enumerable: true, get: function () { return DelegatePay__factory_1.DelegatePay__factory; } });
var ERC1155SingleCollectionUpgradeable__factory_1 = require("./factories/ERC1155SingleCollectionUpgradeable__factory");
Object.defineProperty(exports, "ERC1155SingleCollectionUpgradeable__factory", { enumerable: true, get: function () { return ERC1155SingleCollectionUpgradeable__factory_1.ERC1155SingleCollectionUpgradeable__factory; } });
var ERC1155UpgradeableWrapper__factory_1 = require("./factories/ERC1155UpgradeableWrapper__factory");
Object.defineProperty(exports, "ERC1155UpgradeableWrapper__factory", { enumerable: true, get: function () { return ERC1155UpgradeableWrapper__factory_1.ERC1155UpgradeableWrapper__factory; } });
var ERC721MultiCollectionUpgradeable__factory_1 = require("./factories/ERC721MultiCollectionUpgradeable__factory");
Object.defineProperty(exports, "ERC721MultiCollectionUpgradeable__factory", { enumerable: true, get: function () { return ERC721MultiCollectionUpgradeable__factory_1.ERC721MultiCollectionUpgradeable__factory; } });
var ERC721SingleCollectionUpgradeable__factory_1 = require("./factories/ERC721SingleCollectionUpgradeable__factory");
Object.defineProperty(exports, "ERC721SingleCollectionUpgradeable__factory", { enumerable: true, get: function () { return ERC721SingleCollectionUpgradeable__factory_1.ERC721SingleCollectionUpgradeable__factory; } });
var ERC721UpgradeableWrapper__factory_1 = require("./factories/ERC721UpgradeableWrapper__factory");
Object.defineProperty(exports, "ERC721UpgradeableWrapper__factory", { enumerable: true, get: function () { return ERC721UpgradeableWrapper__factory_1.ERC721UpgradeableWrapper__factory; } });
var CollectionProxy__factory_1 = require("./factories/CollectionProxy__factory");
Object.defineProperty(exports, "CollectionProxy__factory", { enumerable: true, get: function () { return CollectionProxy__factory_1.CollectionProxy__factory; } });
var ERC1155SingleCollectionFactory__factory_1 = require("./factories/ERC1155SingleCollectionFactory__factory");
Object.defineProperty(exports, "ERC1155SingleCollectionFactory__factory", { enumerable: true, get: function () { return ERC1155SingleCollectionFactory__factory_1.ERC1155SingleCollectionFactory__factory; } });
var ERC721MultipleCollectionFactory__factory_1 = require("./factories/ERC721MultipleCollectionFactory__factory");
Object.defineProperty(exports, "ERC721MultipleCollectionFactory__factory", { enumerable: true, get: function () { return ERC721MultipleCollectionFactory__factory_1.ERC721MultipleCollectionFactory__factory; } });
var ERC721SingleCollectionFactory__factory_1 = require("./factories/ERC721SingleCollectionFactory__factory");
Object.defineProperty(exports, "ERC721SingleCollectionFactory__factory", { enumerable: true, get: function () { return ERC721SingleCollectionFactory__factory_1.ERC721SingleCollectionFactory__factory; } });
var ICollection__factory_1 = require("./factories/ICollection__factory");
Object.defineProperty(exports, "ICollection__factory", { enumerable: true, get: function () { return ICollection__factory_1.ICollection__factory; } });
var IFactoryWrapper__factory_1 = require("./factories/IFactoryWrapper__factory");
Object.defineProperty(exports, "IFactoryWrapper__factory", { enumerable: true, get: function () { return IFactoryWrapper__factory_1.IFactoryWrapper__factory; } });
